# -*- coding: utf-8 -*-
"""Fashion_wave_sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kMADz-86_1jIEm716-1Dzoic-KpGnWWm
"""

import os
project_name = "Fashionwave_sales"
root_dir = f"ds_{project_name}"
folders = [
    root_dir,
    f"{root_dir}/csv_files",
    f"{root_dir}/outputs"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Folder structure created!")

"""###This Notebook explores the different aspects of customer behaviour in Fashion sales.The analysis uses a raw dataset.
###The objective is to clean the data, merge datasets, handle missing information, and extract meaningful insights.
"""

!pip install pandas

#import the dataset
import pandas as pd
raw=pd.read_csv("/content/drive/MyDrive/projects/fashionwave_sales/FashionWave_Raw_With_Invoice.csv")
raw.head()

raw.info()
raw.describe()
raw.isnull().sum()
print("Rows, Columns:", raw.shape)

"""##**DATA** **CLEANING and Data Preprocessing**

"""

df = raw.copy()

# covert into numeric
df['UnitPrice'] = pd.to_numeric(df['UnitPrice'], errors='coerce')
df['Cost'] = pd.to_numeric(df['Cost'], errors='coerce')
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Discount'] = pd.to_numeric(df['Discount'], errors='coerce')

# fill missing values to 0
df['Discount'] = df['Discount'].fillna(0)

# Missing customer type -> label as Unknown (keeps rows)
df['CustomerType'] = df['CustomerType'].fillna('Unknown')

# Fill discount policy limit (>30%)
df['PolicyBreach'] = df['Discount'] > 30

# Remove or inspect rows with weird values (negative amounts, NaNs)
bad_rows = df[(df['TransactionAmount'] <= 0) | (df['Quantity'] <= 0) | df[['UnitPrice','Cost']].isnull().any(axis=1)]
print("Potential bad rows count:", bad_rows.shape[0])

# Recalculate transaction-level revenue and profit from raw components
df['TransactionAmount'] = (df['UnitPrice'] * df['Quantity'] * (1 - df['Discount']/100)).round(2)
df['Profit'] = (df['TransactionAmount'] - df['Cost'] * df['Quantity']).round(2)
df.head()

"""##### We recalculate financials to ensure consistency — never trust a pre-computed revenue/profit column without verifying.

##### Flagging policy breaches helps later to show governance issues.

#####Detecting bad rows allows you to choose to drop them or investigate manually.

##**Feature** **Engineering**
"""

import numpy as np
# Date features
df['Date'] = pd.to_datetime(df['Date'])
df['IsWeekend'] = df['Date'].dt.weekday.isin([5,6])
df['Year'] = df['Date'].dt.year
df['WeekNum'] = df['Date'].dt.isocalendar().week
df['YearWeek'] = df['Year'].astype(str) + "-" + df['WeekNum'].astype(str).str.zfill(2)


# Profit margin per transaction
df['ProfitMargin'] = np.where(df['TransactionAmount']>0, (df['Profit'] / df['TransactionAmount']).round(4), 0)


# Discount bins for analysis
bins = [-0.1,0,5,10,15,20,25,30,100]
labels = ['0%','0-5%','5-10%','10-15%','15-20%','20-25%','25-30%','>30%']
df['DiscountBin'] = pd.cut(df['Discount'], bins=bins, labels=labels)

"""#####Profit margin is crucial for profitability analysis and for deciding which SKUs to promote.

#####Discount Bin makes it easy to compute average profit by discount band.
"""

df.head(5)

"""##**Exploratory Data Analysis**

###**Category** **wise** **analysis**
"""

cat_summary = df.groupby('Category').agg(
    Revenue=('TransactionAmount','sum'),
    Profit=('Profit','sum'),
    UnitsSold=('Quantity','sum'),
    Transactions=('InvoiceNo','count'),
    AvgDiscount=('Discount','mean')
).reset_index().sort_values('Revenue', ascending=False)


print("=======Key metrics by category:=====")
cat_summary.head()

"""###**WEEKEND VS WEEKDAYS ANALYSIS**"""

week_summary = df.groupby('IsWeekend').agg(
    Revenue=('TransactionAmount','sum'),
    Profit=('Profit','sum'),
    Transactions=('InvoiceNo','count'),
    AvgAOV=('TransactionAmount','mean')
).reset_index()
print("=====Key metrics for weekend and weekday=====")

week_summary

"""As in analysis it is clearly seen that Average order value for weekend is less than weekdays.So we need to strategies to rasie basket size for weekend.

###**Discount Impact by Bin**
"""

discount_impact = df.groupby('DiscountBin').agg(
    AvgProfit=('Profit','mean'),
    MedianProfit=('Profit','median'),
    Revenue=('TransactionAmount','sum'),
    Count=('InvoiceNo','count')
).reset_index()

print("======Discount Impact====")
discount_impact

"""Average profit declines sharply above 20%.so we need to recommend discount caps and targeted coupon.

###**Store performances(top and bottom)**
"""

store_perf = df.groupby('StoreID').agg(
    Revenue=('TransactionAmount','sum'),
    Profit=('Profit','sum'),
    Transactions=('InvoiceNo','count'),
    AvgAOV=('TransactionAmount','mean')
).reset_index().sort_values('Revenue', ascending=False)


top10_stores = store_perf.head(10)
bottom10_stores = store_perf.tail(10)

"""The idea is to analyse top 10 and botton 10 is to give promotions to the employees where the stores are in top 10.

In botton 10,we need to target local intervention like stock transfer and events.

##**Visualization**
"""

#import libraries
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from scipy.stats import ttest_ind
import statsmodels.api as sm
from statsmodels.formula.api import ols

"""###**Revenue by category**"""

plt.figure(figsize=(8,5))
cat_summary.plot(kind='bar', x='Category', y='Revenue', legend=False)
plt.title("Revenue by Category")
plt.ylabel("Revenue")
plt.show()

"""Total revenue is highest for Men and lowest for women."""

#import libraries for interactive charts
import plotly.express as px
import plotly.graph_objects as go

"""###**Daily Revenue Trend**"""

daily = df.groupby('Date').agg(Revenue=('TransactionAmount', 'sum')).reset_index()

fig = px.line(
    daily,
    x="Date",
    y="Revenue",
    title="Daily Revenue Trend",
    markers=True)

fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Revenue",
    hovermode="x unified",
    template="plotly_white")

fig.show()

"""It can be seen from the chart that revenue jumps for a specific month.It might be the festive season.

###**Profit by Category**
"""

cat_profit = df.groupby("Category").agg(Profit=('Profit','sum')).reset_index()

fig = px.bar(
    cat_profit,
    x="Category",
    y="Profit",
    color="Category",
    title="Profit by Category",
    text_auto=".2s")

fig.update_layout(
    yaxis_title="Total Profit",
    template="plotly_white")
fig.show()

"""###**Weekend vs Weekday revenue**"""

week_summary = df.groupby("IsWeekend").agg(
    Revenue=("TransactionAmount","sum")).reset_index()

week_summary["DayType"] = week_summary["IsWeekend"].map({True:"Weekend", False:"Weekday"})

fig = px.pie(week_summary,names="DayType",values="Revenue",title="Weekend vs Weekday Revenue Share",hole=0.4)

fig.update_traces(textposition="inside", textinfo="percent+label")
fig.show()

"""###**Revenue breakdown by Category**"""

fig = px.sunburst(df,path=["Category", "SubCategory"],values="TransactionAmount",title="Category → SubCategory Revenue Breakdown")

fig.update_layout(template="plotly_white")
fig.show()

"""###**Discount vs Profit**"""

sample = df.sample(4000)

fig = px.scatter(sample,x="Discount",y="Profit",color="Category",size="TransactionAmount",opacity=0.6,
                 title="Discount vs Profit")

fig.update_layout(template="plotly_white")
fig.show()

"""It is clearly seen by the chart that as the discount increase the profit sharply decreses.

###**Weekday and Weekend AOV**
"""

df["AOV"] = df["TransactionAmount"]

fig = px.box(df,x="IsWeekend",y="AOV",color="IsWeekend",title="AOV: Weekday vs Weekend",labels={"IsWeekend": "Weekend (True/False)", "AOV": "Average Order Value"},
    template="plotly_white")

fig.update_xaxes(tickvals=[0,1], ticktext=["Weekday","Weekend"])
fig.show()

"""###**Revenue by Discount**"""

disc = df.groupby("DiscountBin").agg(Revenue=("TransactionAmount","sum"),Profit=("Profit","sum")).reset_index()

fig = px.bar(disc,x="DiscountBin",y="Revenue",color="Profit",title="Revenue by Discount Range",text_auto=True)

fig.update_layout(template="plotly_white")
fig.show()

"""###**Weekly Sales Trend**"""

weekly = df.groupby("YearWeek").agg(Revenue=("TransactionAmount","sum")).reset_index()

fig = px.line(weekly,x="YearWeek",y="Revenue",title="Weekly Sales Trend",markers=True)

fig.update_layout(xaxis_title="Year-Week",yaxis_title="Revenue",template="plotly_white")

fig.show()

"""#**Statistical Test**

###**t-statistics**
"""

weekday_amt = df[df['IsWeekend']==False]['TransactionAmount']
weekend_amt = df[df['IsWeekend']==True]['TransactionAmount']

# Use t-test for large-sample approximate inference. If non-normal, consider Mann-Whitney.
tstat, pval = ttest_ind(weekday_amt, weekend_amt, equal_var=False)
print("t-stat:", tstat, "p-value:", pval)

"""t-stat: -0.7884365168495443

This suggests weekend transaction amounts are slightly higher than weekday amounts on average.However, the value is very close to zero, indicating a very small difference

p-value: 0.4304484965738612

This is much greater than the typical significance level of 0.05 There's a 43.5% probability that any observed difference is due to random chance.



*   Any small difference observe in the data is likely just random variation.Customers don't spend significantly more or less on weekends compared to weekdays.

###**ANOVA**
"""

#Does discount bins affect profit
df_anova = df.dropna(subset=['DiscountBin'])
model = ols('Profit ~ C(DiscountBin)', data=df_anova).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print(anova_table)

"""as p < 0.05,Discount bins have a statistically significant effect on profit. Different discount levels lead to significantly different profit outcomes.



*   Some discount ranges are MUCH more profitable than others.

*   Discount strategy CRITICALLY impacts bottom-line profits.

*   We shouldd optimize discount offerings based on which   bins generate the highest profits.



"""

# for Power bi
weekly_kpis = df.groupby(['StoreID','StoreCity','Year','WeekNum','YearWeek']).agg(
    TotalSales=('TransactionAmount','sum'),
    WeekendSales=('TransactionAmount', lambda x: x[df.loc[x.index,'IsWeekend']].sum()),
    TotalProfit=('Profit','sum'),
    Transactions=('InvoiceNo','count'),
    UnitsSold=('Quantity','sum'),
    AvgAOV=('TransactionAmount','mean'),
    AvgDiscount=('Discount','mean')
).reset_index()

weekly_kpis['WeekendRatio'] = weekly_kpis['WeekendSales'] / weekly_kpis['TotalSales']
weekly_kpis.head()

#saving csv fiiles to dir
csv_path= f"{root_dir}/csv_files/df.csv"
df.to_csv(csv_path, index=False)

csv_path= f"{root_dir}/csv_files/raw.csv"
raw.to_csv(csv_path, index=False)

csv_path= f"{root_dir}/csv_files/cat_summary.csv"
cat_summary.to_csv(csv_path, index=False)

csv_path= f"{root_dir}/csv_files/week_summary.csv"
week_summary.to_csv(csv_path, index=False)

csv_path= f"{root_dir}/csv_files/discount_impact.csv"
discount_impact.to_csv(csv_path, index=False)

csv_path= f"{root_dir}/csv_files/top10_stores.csv"
top10_stores.to_csv(csv_path, index=False)

csv_path= f"{root_dir}/csv_files/bottom10_stores.csv"
bottom10_stores.to_csv(csv_path, index=False)

csv_path= f"{root_dir}/csv_files/weekly_kpis.csv"
weekly_kpis.to_csv(csv_path, index=False)

plot_path=f"{root_dir}/outputs/weekly sales trend.png"
plt.savefig(plot_path)

plot_path=f"{root_dir}/outputs/revenue by discount.png"
plt.savefig(plot_path)

plot_path=f"{root_dir}/outputs/AOV:weekday vs weekend.png"
plt.savefig(plot_path)

plot_path=f"{root_dir}/outputs/discount vs profit.png"
plt.savefig(plot_path)

plot_path=f"{root_dir}/outputs/subcategory revenue breakdown.png"
plt.savefig(plot_path)

plot_path=f"{root_dir}/outputs/weekend bs weekday revenue share.png"
plt.savefig(plot_path)

plot_path=f"{root_dir}/outputs/Revene by category.png"
plt.savefig(plot_path)

plot_path=f"{root_dir}/outputs/profit by category.png"
plt.savefig(plot_path)

plot_path=f"{root_dir}/outputs/daily revenue trend.png"
plt.savefig(plot_path)